In [1]:
import pandas as pd
import os
import ffmpeg
import bar_chart_race as bcr

In [2]:
df = pd.read_csv("Video_Games.csv")

In [3]:
df.describe()

,Year_of_Release,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Count
count,16450.000000,16719.000000,16719.000000,16719.000000,16719.000000,16719.000000,8137.000000,8137.000000,7590.000000
mean,2006.487356,0.263330,0.145025,0.077602,0.047332,0.533543,68.967679,26.360821,162.229908
std,5.878995,0.813514,0.503283,0.308818,0.186710,1.547935,13.938165,18.980495,561.282326
min,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000,13.000000,3.000000,4.000000
25%,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000,60.000000,12.000000,10.000000
50%,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000,71.000000,21.000000,24.000000
75%,2010.000000,0.240000,0.110000,0.040000,0.030000,0.470000,79.000000,36.000000,81.000000
max,2020.000000,41.360000,28.960000,10.220000,10.570000,82.530000,98.000000,113.000000,10665.000000

In [4]:
df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
sales = df.iloc[:, [0,1,2,9]]

In [6]:
sales.isna().sum()

Name                 2
Platform             0
Year_of_Release    269
Global_Sales         0
dtype: int64

In [7]:
yearless=sales.loc[sales['Year_of_Release'].isna() == True]
hasyear=sales.notna()

In [8]:
hasyear.describe()

         Name Platform Year_of_Release Global_Sales
count   16719    16719           16719        16719
unique      2        1               2            1
top      True     True            True         True
freq    16717    16719           16450        16719

In [9]:
print(yearless.iloc[:,0:2].values)

[['Madden NFL 2004' 'PS2']
 ['FIFA Soccer 2004' 'PS2']
 ['LEGO Batman: The Videogame' 'Wii']
 ['wwe Smackdown vs. Raw 2006' 'PS2']
 ['Space Invaders' '2600']
 ['Rock Band' 'X360']
 ["Frogger's Adventures: Temple of the Frog" 'GBA']
 ['LEGO Indiana Jones: The Original Adventures' 'Wii']
 ['Call of Duty 3' 'Wii']
 ['Rock Band' 'Wii']
 ['Call of Duty: Black Ops' 'PC']
 ['Rock Band' 'PS3']
 ['Triple Play 99' 'PS']
 ['Adventure' '2600']
 ['LEGO Batman: The Videogame' 'PSP']
 ['Combat' '2600']
 ['LEGO Harry Potter: Years 5-7' 'Wii']
 ['NASCAR Thunder 2003' 'PS2']
 ['Hitman 2: Silent Assassin' 'XB']
 ['Rock Band' 'PS2']
 ['Legacy of Kain: Soul Reaver' 'PS']
 ['Donkey Kong Land III' 'GB']
 ['Air-Sea Battle' '2600']
 ['Suikoden III' 'PS2']
 ['LEGO Harry Potter: Years 5-7' 'X360']
 ['Wheel of Fortune' 'PS2']
 ['Yakuza 4' 'PS3']
 ['LEGO Harry Potter: Years 5-7' 'PS3']
 ['Namco Museum' 'XB']
 ['Rhythm Heaven' 'Wii']
 ['The Lord of the Rings: War in the North' 'X360']
 ['Madden NFL 07' 'PSP']
 ['MLB SlugFest 20-03' 'PS2']
 ['The Lord of the Rings: War in the North' 'PS3']
 ['Shaun White Snowboarding' 'X360']
 ['PES 2009: Pro Evolution Soccer' 'PSP']
 ['WarioWare: Twisted!' 'GBA']
 ['Madden NFL 11' 'Wii']
 ['Test Drive Unlimited 2' 'X360']
 ['The Chronicles of Narnia: The Lion, The Witch and The Wardrobe' 'GBA']
 ['LEGO Harry Potter: Years 5-7' 'DS']
 ['Monster Hunter 2' 'PS2']
 ['Metal Gear Solid 2: Substance' 'XB']
 ['Test Drive Unlimited 2' 'PS3']
 ['Advance Wars: Days of Ruin' 'DS']
 ['The Golden Compass' 'Wii']
 ['Madden NFL 06' 'X360']
 ['NASCAR: Dirt to Daytona' 'PS2']
 ['Madden NFL 2002' 'XB']
 ['Def Jam: Fight for NY' 'XB']
 ['NBA Street Vol. 2' 'GC']
 ['Fishing Derby' '2600']
 ['Wet' 'X360']
 ['Sonic the Hedgehog' 'PS3']
 ['Karate' '2600']
 ['Tiger Woods PGA Tour 07' 'Wii']
 ['Circus Atari' '2600']
 ['The Chronicles of Riddick: Escape from Butcher Bay' 'XB']
 ["Maze Craze: A Game of Cops 'n Robbers" '2600']
 ['Silent Hill: Homecoming' 'X360']
 ['Super Breakout' '2600']
 ["Robert Ludlum's The Bourne Conspiracy" 'X360']
 ['NHL Slapshot' 'Wii']
 ['TERA' 'PC']
 ['NFL GameDay 2003' 'PS2']
 ['LEGO Harry Potter: Years 5-7' '3DS']
 ['Harvest Moon: Save the Homeland' 'PS2']
 ["Robert Ludlum's The Bourne Conspiracy" 'PS3']
 ['Silent Hill: Homecoming' 'PS3']
 ['Hangman' '2600']
 ['The Golden Compass' 'PSP']
 ['NBA Live 2003' 'XB']
 ["Cubix Robots for Everyone: Clash 'n' Bash" 'GBA']
 ['Dragon Ball Z: Budokai Tenkaichi 2 (JP sales)' 'Wii']
 ['Tropico 4' 'X360']
 ['Tomb Raider (2013)' 'PC']
 ['Bejeweled 3' 'DS']
 ['Custom Robo' 'N64']
 ['Final Fantasy XI' 'PS2']
 ['Singularity' 'X360']
 ['Dragster' '2600']
 ['All-Star Baseball 2005' 'PS2']
 ['Star Wars Jedi Knight II: Jedi Outcast' 'XB']
 ['Slot Machine' '2600']
 ['The Dukes of Hazzard II: Daisy Dukes It Out' 'PS']
 ['Harvest Moon: The Tale of Two Towns' '3DS']
 ['NBA Live 2003' 'GC']
 ['Shrek the Third' 'DS']
 ['Nicktoons: Battle for Volcano Island' 'GC']
 ['Haven: Call of the King' 'PS2']
 ['Unreal Championship 2: The Liandri Conflict' 'XB']
 ['The Chronicles of Narnia: The Lion, The Witch and The Wardrobe' 'GC']
 ['Pac-Man Fever' 'GC']
 ['The Legend of Zelda: The Minish Cap(weekly JP sales)' 'GBA']
 ['Indy 500' '2600']
 ['Disgaea 3: Absence of Detention' 'PSV']
 ['Flag Capture' '2600']
 ['Gun' 'X360']
 ['Rock Revolution' 'PS3']
 ['LEGO Harry Potter: Years 5-7' 'PSP']
 ['College Hoops 2K6' 'PS2']
 ['Jonah Lomu Rugby Challenge' 'PS3']
 ['Mega Man X Collection' 'PS2']
 ['BioShock 2' 'PC']
 ['Singularity' 'PS3']
 ['Danganronpa: Trigger Happy Havoc' 'PSP']
 ['Jet X20' 'PS2']
 ["Tony Hawk's Downhill Jam" 'Wii']
 ['Tribes: Aerial Assault' 'PS2']
 ['Big Beach Sports 2' 'Wii']
 ['LEGO Harry Potter: Years 5-7' 'PC']
 ['Yu Yu Hakusho: Dark Tournament' 'PS2']
 ['Ghostbusters II' '2600']
 ['Breakaway IV' '2600']
 ['Robotech: Battlecry' 'XB']
 ['Move Fitness' 'PS3']
 ['Valkyria Chronicles III: Unrecorded Chronicles' 'PSP']
 ['DanceDanceRevolution II' 'Wii']
 ['WRC: FIA World Rally Championship' 'PS3']
 ['Famista 64' 'N64']
 ['Dead Space 3' 'PC']
 ['Test Drive Unlimited 2' 'PC']
 ['Pet Zombies' '3DS']
 ['Star Trek: Legacy' 'X360']
 ['Backbreaker' 'X360']
 ['Twisted Metal: Small Brawl' 'PS']
 ['Otomedius Excellent' 'X360']
 ['NBA Starting Five' 'PS2']
 ['Teen Titans' 'GBA']
 ['Trauma Team' 'Wii']
 ['Backbreaker' 'PS3']
 ["James Cameron's Dark Angel" 'PS2']
 ['Sword of the Samurai' 'PS2']
 ['Splatterhouse' 'PS3']
 ['Alone in the Dark: The New Nightmare' 'PS']
 ['Vegas Party' 'Wii']
 ['Jurassic Park: The Game' 'X360']
 ['Home Run' '2600']
 ['eJay Clubworld' 'PS2']
 ['All-Star Baseball 2005' 'XB']
 ['Bejeweled 3' 'PS3']
 ['Our House Party!' 'Wii']
 ['WCW Backstage Assault' 'N64']
 ['Bejeweled 3' 'X360']
 ["Disney's Cinderella: Magical Dreams" 'GBA']
 ['Transworld Surf' 'XB']
 ['Street Fighter IV' 'PC']
 ['Nintendo Puzzle Collection' 'GC']
 ['Charm Girls Club: My Fashion Mall' 'DS']
 ['Record of Agarest War Zero' 'PS3']
 ['Rocksmith' 'PC']
 ['Super Robot Wars OG Saga: Masou Kishin II - Revelation of Evil God'
  'PSP']
 ['Saru! Get You! Million Monkeys' 'PS2']
 ['Street Hoops' 'GC']
 ['WRC: FIA World Rally Championship' 'X360']
 ['Godzilla: Destroy All Monsters Melee' 'XB']
 ['The Daring Game for Girls' 'DS']
 ['Major League Baseball 2K6' 'PSP']
 ['Star Trek: Conquest' 'PS2']
 ['GiFTPiA' 'GC']
 ['Happy Feet Two' 'PS3']
 ["Disney's Chicken Little: Ace In Action" 'Wii']
 ['Atsumare! Power Pro Kun no DS Koushien' 'DS']
 ['My Healthy Cooking Coach' 'DS']
 ['Happy Feet Two' 'DS']
 ['Luminous Arc 2 (JP sales)' 'DS']
 ['Happy Feet Two' 'X360']
 ['Egg Monster Hero' 'DS']
 ['The Daring Game for Girls' 'Wii']
 ['Demon Chaos' 'PS2']
 ['Samurai Shodown Anthology' 'PSP']
 ['Action Man-Operation Extreme' 'PS']
 ['Super Puzzle Fighter II' 'GBA']
 ['Charm Girls Club: My Fashion Show' 'DS']
 ['Face Racers: Photo Finish' '3DS']
 ['Zero: Tsukihami no Kamen' 'Wii']
 ['The Hidden' '3DS']
 ['Get Fit with Mel B' 'X360']
 ['Rock Revolution' 'Wii']
 ['Happy Feet Two' 'Wii']
 ['Mega Man Battle Network: Operation Shooting Star' 'DS']
 ['Smashing Drive' 'GC']
 ['Port Royale 3' 'PS3']
 ['Dream Trigger 3D' '3DS']
 ['Dead Island: Riptide' 'PC']
 ['Yoostar on MTV' 'X360']
 ['Tornado' 'DS']
 ["McFarlane's Evil Prophecy" 'PS2']
 ['Drake of the 99 Dragons' 'XB']
 ['Build-A-Bear Workshop: Friendship Valley' 'Wii']
 ['Rayman Arena' 'XB']
 ['Port Royale 3' 'X360']
 ['National Geographic Challenge!' 'X360']
 ['Alex Rider: Stormbreaker' 'DS']
 ['Chou Soujuu Mecha MG' 'DS']
 ['Prinny: Can I Really Be The Hero? (US sales)' 'PSP']
 ['Combat Elite: WWII Paratroopers' 'PS2']
 ["Flip's Twisted World" 'Wii']
 ['Mobile Ops: The One Year War' 'X360']
 ["Tom Clancy's Rainbow Six: Critical Hour" 'XB']
 ['Jewel Link Chronicles: Mountains of Madness' 'DS']
 ['Captain America: Super Soldier' 'Wii']
 ['Mountain Bike Adrenaline' 'PS2']
 ['Drill Dozer' 'GBA']
 ['Captain America: Super Soldier' 'DS']
 ['GRID' 'DS']
 ['Tour de France 2011' 'X360']
 ['Reader Rabbit 2nd Grade' 'Wii']
 ['Monster Hunter Frontier Online' 'PS3']
 ['RollerCoaster Tycoon' 'PC']
 ['Battle vs. Chess' 'PS3']
 ['The History Channel: Great Battles - Medieval' 'PS3']
 ['Clockwork Empires' 'PC']
 ['B.L.U.E.: Legend of Water' 'PS']
 ['GRID' 'PC']
 ['NHL Hitz Pro' 'GC']
 ["Luxor: Pharaoh's Challenge" 'Wii']
 ['Sega Rally 2006' 'PS2']
 ['Half-Minute Hero 2' 'PSP']
 ['Housekeeping' 'DS']
 ['Major League Baseball 2K8' 'PSP']
 ['Sabre Wulf' 'GBA']
 ['Swords' 'Wii']
 ['Beyond the Labyrinth' '3DS']
 ['Bikkuriman Daijiten' 'DS']
 ['Majesty 2: The Fantasy Kingdom Sim' 'X360']
 ['Fullmetal Alchemist: Brotherhood' 'PSP']
 ['Combat Elite: WWII Paratroopers' 'XB']
 ['Samurai Spirits: Tenkaichi Kenkakuden' 'PS2']
 ['World of Tanks' 'X360']
 ['Battle vs. Chess' 'PC']
 ['Tom and Jerry in War of the Whiskers' 'XB']
 ['Super Duper Sumos' 'GBA']
 ['The King of Fighters: Maximum Impact - Maniax' 'XB']
 ['Combat Wings: The Great Battles of WWII' 'Wii']
 ['Tube Slider' 'GC']
 ['Umineko no Naku Koro ni San: Shinjitsu to Gensou no Yasoukyoku' 'PS3']
 ['Payout Poker & Casino' 'PSP']
 ['Wii de Asobu: Metroid Prime' 'Wii']
 ['Legacy of Ys: Books I & II' 'DS']
 ['Saint' 'Wii']
 ['Steal Princess' 'DS']
 ['Mario Tennis' '3DS']
 ['Runaway: A Twist of Fate' 'DS']
 ["Yu-Gi-Oh! 5D's Wheelie Breakers (JP sales)" 'Wii']
 ["Cabela's Alaskan Adventure" 'PS2']
 ['Writing and Speaking Beautiful Japanese DS' 'DS']
 ['Virtua Quest' 'PS2']
 ["Shonen Jump's Yu-Gi-Oh! GX Card Almanac" 'DS']
 ['Without Warning' 'XB']
 ['PDC World Championship Darts 2008' 'DS']
 ['Dinotopia: The Sunstone Odyssey' 'GC']
 ['Jet Impulse' 'DS']
 ['Dream Dancer' 'DS']
 ["Dance! It's Your Stage" 'Wii']
 ['Football Manager 2007' 'X360']
 ['Ferrari: The Race Experience' 'Wii']
 ['Aquaman: Battle for Atlantis' 'XB']
 ['WRC: FIA World Rally Championship' 'PC']
 ['Homeworld Remastered Collection' 'PC']
 ['Shorts' 'DS']
 ['AKB1/48: Idol to Guam de Koishitara...' 'X360']
 ['Brothers in Arms: Furious 4' 'X360']
 ['Agarest Senki: Re-appearance' 'PS3']
 ['PDC World Championship Darts 2008' 'PSP']
 ['Freaky Flyers' 'GC']
 ['Inversion' 'PC']
 ['Hakuouki: Shinsengumi Kitan' 'PS3']
 ['Virtua Quest' 'GC']]

In [10]:
sales

                                Name Platform  Year_of_Release  Global_Sales
0                         Wii Sports      Wii           2006.0         82.53
1                  Super Mario Bros.      NES           1985.0         40.24
2                     Mario Kart Wii      Wii           2008.0         35.52
3                  Wii Sports Resort      Wii           2009.0         32.77
4           Pokemon Red/Pokemon Blue       GB           1996.0         31.37
...                              ...      ...              ...           ...
16714  Samurai Warriors: Sanada Maru      PS3           2016.0          0.01
16715               LMA Manager 2007     X360           2006.0          0.01
16716        Haitaka no Psychedelica      PSV           2016.0          0.01
16717               Spirits & Spells      GBA           2003.0          0.01
16718            Winning Post 8 2016      PSV           2016.0          0.01

[16719 rows x 4 columns]

In [11]:
sales['Rank'] = sales['Global_Sales'].rank()

C:\Users\JKim\AppData\Local\Temp\ipykernel_10620\2813278350.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales['Rank'] = sales['Global_Sales'].rank()

In [12]:
sales = sales.sort_values(by='Global_Sales', ascending=False)
sales

,Name,Platform,Year_of_Release,Global_Sales,Rank
0,Wii Sports,Wii,2006.0,82.53,16719.0
1,Super Mario Bros.,NES,1985.0,40.24,16718.0
2,Mario Kart Wii,Wii,2008.0,35.52,16717.0
3,Wii Sports Resort,Wii,2009.0,32.77,16716.0
4,Pokemon Red/Pokemon Blue,GB,1996.0,31.37,16715.0
...,...,...,...,...,...
16294,Simple 2000 Series Vol. 120: The Saigo no Nipp...,PS2,2007.0,0.01,319.5
16295,Casper,GBA,2002.0,0.01,319.5
16296,AKB1/48: Idol to Guam de Koishitara...,X360,NaN,0.01,319.5
16297,Adventure Time: The Secret of the Nameless,X360,2014.0,0.01,319.5
16718,Winning Post 8 2016,PSV,2016.0,0.01,319.5

In [13]:
sales.set_index('Year_of_Release', inplace = True)

In [14]:
bcr.bar_chart_race(df=sales,filename=None,title= "Global Top-Selling Videogames by Year")

C:\Users\JKim\AppData\Local\anaconda3\Lib\site-packages\bar_chart_race\_make_chart.py:893: FutureWarning: Dropping of nuisance columns in DataFrame.rank is deprecated; in a future version this will raise TypeError. Select only valid columns before calling rank.
  df_ranks = df_values.rank(axis=1, method='first', ascending=False).clip(upper=n_bars + 1)
C:\Users\JKim\AppData\Local\anaconda3\Lib\site-packages\bar_chart_race\_make_chart.py:278: FutureWarning: The default value of numeric_only in DataFrame.max is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  max_val = self.df_values.max().max()
C:\Users\JKim\AppData\Local\anaconda3\Lib\site-packages\bar_chart_race\_make_chart.py:286: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_yticklabels(self.df_values.columns)
C:\Users\JKim\AppData\Local\anaconda3\Lib\site-packages\bar_chart_race\_make_chart.py:287: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels([max_val] * len(ax.get_xticks()))

Exception: You do not have ffmpeg installed on your machine. Download
                            ffmpeg from here: https://www.ffmpeg.org/download.html.

                            Matplotlib's original error message below:

                            boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 2